# Change these first
owner: sourcequality # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: youmust.watch
    url: https://youmust.watch
  - name: youmust.watch Requests
    url: https://requests.youmust.watch
  - name: youmust.watch Accounts
    url: https://auth.youmust.watch
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.youmust.watch
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "The you know what status page"
  introMessage: Powered by [Upptime](https://github.com/upptime/upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
